# Generated by Django 5.0.1 on 2024-08-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_photo', models.BinaryField(null=True)),
                ('image', models.BinaryField()),
                ('employee_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_bank_ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
