# Generated by Django 5.0.1 on 2024-08-16 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_employee_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofencedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.FloatField(help_text='Radius in meters')),
            ],
        ),
        migrations.CreateModel(
            name='mark_attendance_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_photo', models.BinaryField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='employee_photo',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='image',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='employee_image_encodeing',
            field=models.TextField(null=True),
        ),
    ]
